name: Auto Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: ready, merge, approvado, integrar, lancar, pronto, liberar merge, com automerge
          blocking_labels: do not merge, dont-merge, bloquear merge, sem automerge
          checks_enabled: false
          method: merge
          delete_source_branch: true
