# Test if the new commits has the version bump for deploy works
name: Check new version
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - production
      - main

jobs:
  save-current-version:
    runs-on: ubuntu-latest
    name: Save Envs
    steps:
      - name: Save Enviroment
        id: trigger_version
        run: |
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
          echo $PACKAGE_VERSION
          echo "::set-output name=triggered_version::$PACKAGE_VERSION"

  go-to-main:
    runs-on: ubuntu-latest
    name: Go to main branch
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run version check
        run: |
          cd .semver
          npm i
          cd ../
          node .semver/ ${{ needs.trigger_version.outputs.triggered_version }}
