name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  publish:
    environment:
      name: Deploy Enviroment
    env:
      VSCE_DEPLOY_TOKEN: ${{ secrets.VSCE_DEPLOY_TOKEN }} # set visual studio deploy token globally
    name: Deploy extension to production, with node 12 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set enviroment variables
        id: vars
        # will be available at title: ${{ steps.vars.outputs.pr_title }}
        run: |
          echo ::set-output name=package_version::$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          echo "Current version "$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
      - name: npm install and publish
        run: |
          npm install
          npm test
          npm run publish
      # Generate release at releases page
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "*.vsix"
          name: ${{ steps.vars.outputs.package_version }}
          body: ./CHANGELOG.md
          tag: ${{ steps.vars.outputs.package_version }}
