name: Deploy to Production

env:
  VSCE_DEPLOY_TOKEN: ${{ secrets.VSCE_DEPLOY_TOKEN }} # set visual studio deploy token globally
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Deploy extension to production, with node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ["12"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Set enviroment variables
        id: vars
        # will be available at title: ${{ steps.vars.outputs.pr_title }}
        run: |
          echo ::set-output name=package_version::$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          echo "Current version ${{ steps.vars.outputs.package_version }}"
          echo ::set-output name=changes_summary::$(sed --expression='1,/##/d;/### 0.1/Q' CHANGELOG.md)
          echo "Current changes ${{ steps.vars.outputs.changes_summary }}"
      - name: npm install and publish
        run: |
          npm install
          npm test
          npm run publish
      # Generate release at releases page
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "*.vsix"
          name: ${{ steps.vars.outputs.package_version }}
          body: ${{ steps.vars.outputs.changes_summary }}
          tag: ${{ steps.vars.outputs.package_version }}
